
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int bool = 10;
  public static final int not = 2;
  public static final int par_c = 6;
  public static final int or = 4;
  public static final int EOF = 0;
  public static final int and = 3;
  public static final int par_a = 5;
  public static final int tr = 8;
  public static final int error = 1;
  public static final int fl = 9;
  public static final int punto_coma = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "not",
  "and",
  "or",
  "par_a",
  "par_c",
  "punto_coma",
  "tr",
  "fl",
  "bool"
  };
}

